global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "todo-api"
    static_configs:
      - targets: ["localhost:3000"]  # ← Porque están en la misma task
    metrics_path: /metrics

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "alertmanager"
    static_configs:
      - targets: ["localhost:9093"]